from __future__ import annotations

import argparse
import json
import re
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class Finding:
    code: str
    severity: str
    reason: str


def main() -> None:
    parser = argparse.ArgumentParser(description="Analyze shadow replay reports and flag suspicious conversational cases.")
    parser.add_argument("report", type=Path, help="JSONL report generated by scripts/replay_chatwoot_conversations.py")
    parser.add_argument("--limit", type=int, default=40, help="Maximum flagged rows to print")
    parser.add_argument("--json", action="store_true", help="Print machine-readable JSON instead of text")
    parser.add_argument("--markdown-output", type=Path, default=None, help="Write a Markdown review report to this path.")
    parser.add_argument("--json-output", type=Path, default=None, help="Write machine-readable JSON analysis to this path.")
    parser.add_argument("--full-markdown-output", type=Path, default=None, help="Write a Markdown report with every replayed turn.")
    parser.add_argument("--full-answer-limit", type=int, default=1800, help="Maximum characters per old/new answer in the full Markdown report.")
    args = parser.parse_args()

    rows = load_rows(args.report)
    analyzed = [(row, analyze_row(row)) for row in rows]
    flagged = [(row, findings) for row, findings in analyzed if findings]

    summary = build_summary(rows, analyzed, flagged)
    payload = analysis_payload(summary, flagged, args.limit)
    if args.json_output:
        args.json_output.parent.mkdir(parents=True, exist_ok=True)
        args.json_output.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    if args.markdown_output:
        args.markdown_output.parent.mkdir(parents=True, exist_ok=True)
        args.markdown_output.write_text(markdown_report(args.report, summary, flagged, args.limit), encoding="utf-8")
    if args.full_markdown_output:
        args.full_markdown_output.parent.mkdir(parents=True, exist_ok=True)
        args.full_markdown_output.write_text(
            full_markdown_report(args.report, summary, analyzed, args.full_answer_limit),
            encoding="utf-8",
        )

    if args.json:
        print(json.dumps(payload, ensure_ascii=False, indent=2))
        return

    print_text_report(args.report, summary, flagged, args.limit)


def load_rows(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with path.open(encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError as exc:
                raise SystemExit(f"{path}:{line_number}: invalid JSONL: {exc}") from exc
            if isinstance(row, dict):
                rows.append(row)
    return rows


def build_summary(
    rows: list[dict[str, Any]],
    analyzed: list[tuple[dict[str, Any], list[Finding]]],
    flagged: list[tuple[dict[str, Any], list[Finding]]],
) -> dict[str, Any]:
    finding_counts = Counter(finding.code for _, findings in analyzed for finding in findings)
    severity_counts = Counter(finding.severity for _, findings in analyzed for finding in findings)
    intents = Counter(((row.get("intake") or {}).get("intent") or "None") for row in rows)
    routes = Counter(((row.get("route") or {}).get("action") or "legacy") for row in rows)
    should_search = Counter(bool((row.get("intake") or {}).get("should_search")) for row in rows)
    return {
        "rows": len(rows),
        "flagged_rows": len(flagged),
        "conversations": len({str(row.get("conversation_id")) for row in rows if row.get("conversation_id") is not None}),
        "rows_with_agent": sum(1 for row in rows if isinstance(row.get("agent"), dict)),
        "rows_with_expected": sum(1 for row in rows if row.get("expected_assistant")),
        "errors": sum(1 for row in rows if row.get("error")),
        "tool_calls": sum(len(tool_calls(row)) for row in rows),
        "rows_with_tools": sum(1 for row in rows if tool_calls(row)),
        "intents": dict(intents),
        "routes": dict(routes),
        "should_search": {str(key): value for key, value in should_search.items()},
        "finding_counts": dict(finding_counts),
        "severity_counts": dict(severity_counts),
    }


def print_text_report(
    report_path: Path,
    summary: dict[str, Any],
    flagged: list[tuple[dict[str, Any], list[Finding]]],
    limit: int,
) -> None:
    print(f"report={report_path}")
    print(
        "summary "
        f"conversations={summary['conversations']} "
        f"rows={summary['rows']} "
        f"rows_with_agent={summary['rows_with_agent']} "
        f"rows_with_expected={summary['rows_with_expected']} "
        f"flagged={summary['flagged_rows']} "
        f"errors={summary['errors']} "
        f"tool_calls={summary['tool_calls']} "
        f"rows_with_tools={summary['rows_with_tools']}"
    )
    print(f"intents={summary['intents']}")
    print(f"routes={summary['routes']}")
    print(f"should_search={summary['should_search']}")
    print(f"findings={summary['finding_counts']}")
    print()

    for index, (row, findings) in enumerate(flagged[:limit], start=1):
        print(f"{index}. conversation={row.get('conversation_id')} message={row.get('message_id')}")
        print("   " + ", ".join(f"{finding.severity}:{finding.code}" for finding in findings))
        print(f"   user: {one_line(row.get('user_message'), 220)}")
        expected = row.get("expected_assistant")
        if expected:
            print(f"   old: {one_line(expected, 360)}")
        answer = (row.get("agent") or {}).get("answer")
        if answer:
            print(f"   new: {one_line(answer, 360)}")
        if tool_calls(row):
            print(f"   tools: {tool_calls(row)}")
        print(f"   state_after: {compact_state(row.get('state_after'))}")
        print()


def analysis_payload(
    summary: dict[str, Any],
    flagged: list[tuple[dict[str, Any], list[Finding]]],
    limit: int,
) -> dict[str, Any]:
    return {
        "summary": summary,
        "flagged": [
            {
                "conversation_id": row.get("conversation_id"),
                "message_id": row.get("message_id"),
                "user_message": row.get("user_message"),
                "old_answer": row.get("expected_assistant"),
                "new_answer": (row.get("agent") or {}).get("answer"),
                "intake": row.get("intake"),
                "state_before": row.get("state_before"),
                "state_after": row.get("state_after"),
                "tool_calls": (row.get("agent") or {}).get("tool_calls") or [],
                "findings": [finding.__dict__ for finding in findings],
            }
            for row, findings in flagged[:limit]
        ],
    }


def markdown_report(
    report_path: Path,
    summary: dict[str, Any],
    flagged: list[tuple[dict[str, Any], list[Finding]]],
    limit: int,
) -> str:
    lines = [
        "# Chatwoot Replay Analysis",
        "",
        f"- Source report: `{report_path}`",
        f"- Conversations: {summary['conversations']}",
        f"- User turns: {summary['rows']}",
        f"- Turns with new agent answer: {summary['rows_with_agent']}",
        f"- Turns with old answer available: {summary['rows_with_expected']}",
        f"- Flagged turns: {summary['flagged_rows']}",
        f"- Runtime errors: {summary['errors']}",
        f"- Tool calls: {summary['tool_calls']}",
        f"- Turns with tools: {summary['rows_with_tools']}",
        "",
        "## Intents",
        "",
        *[f"- `{name}`: {count}" for name, count in sorted(summary["intents"].items())],
        "",
        "## Routes",
        "",
        *[f"- `{name}`: {count}" for name, count in sorted(summary["routes"].items())],
        "",
        "## Findings",
        "",
    ]
    if summary["finding_counts"]:
        lines.extend(f"- `{name}`: {count}" for name, count in sorted(summary["finding_counts"].items()))
    else:
        lines.append("- No suspicious findings.")
    lines.extend(["", f"## Flagged Cases (first {min(limit, len(flagged))})", ""])

    for index, (row, findings) in enumerate(flagged[:limit], start=1):
        lines.extend(
            [
                f"### {index}. Conversation `{row.get('conversation_id')}` / Message `{row.get('message_id')}`",
                "",
                "**Findings:** "
                + ", ".join(f"`{finding.severity}:{finding.code}`" for finding in findings),
                "",
                f"**User:** {one_line(row.get('user_message'), 700)}",
                "",
            ]
        )
        expected = row.get("expected_assistant")
        if expected:
            lines.extend(["**Old answer:**", "", blockquote(expected, 1200), ""])
        answer = (row.get("agent") or {}).get("answer")
        if answer:
            lines.extend(["**New answer:**", "", blockquote(answer, 1200), ""])
        calls = tool_calls(row)
        if calls:
            lines.extend(["**Tool calls:**", "", f"```json\n{json.dumps(calls, ensure_ascii=False, indent=2)}\n```", ""])
        lines.extend(["**State after:**", "", f"```json\n{compact_state_json(row.get('state_after'))}\n```", ""])

    return "\n".join(lines).rstrip() + "\n"


def full_markdown_report(
    report_path: Path,
    summary: dict[str, Any],
    analyzed: list[tuple[dict[str, Any], list[Finding]]],
    answer_limit: int,
) -> str:
    lines = [
        "# Full Agent Replay Review",
        "",
        f"- Source report: `{report_path}`",
        f"- Conversations: {summary['conversations']}",
        f"- User turns: {summary['rows']}",
        f"- Turns with new agent answer: {summary['rows_with_agent']}",
        f"- Flagged turns: {summary['flagged_rows']}",
        f"- Runtime errors: {summary['errors']}",
        f"- Tool calls: {summary['tool_calls']}",
        "",
        "## Route Summary",
        "",
        *[f"- `{name}`: {count}" for name, count in sorted(summary["routes"].items())],
        "",
        "## Intent Summary",
        "",
        *[f"- `{name}`: {count}" for name, count in sorted(summary["intents"].items())],
        "",
        "## Conversations",
        "",
    ]

    grouped: dict[str, list[tuple[dict[str, Any], list[Finding]]]] = {}
    for row, findings in analyzed:
        grouped.setdefault(str(row.get("conversation_id")), []).append((row, findings))

    for conversation_index, (conversation_id, rows) in enumerate(grouped.items(), start=1):
        lines.extend([f"### Conversation {conversation_index}: `{conversation_id}`", ""])
        for turn_index, (row, findings) in enumerate(rows, start=1):
            route = row.get("route") if isinstance(row.get("route"), dict) else {}
            intake = row.get("intake") if isinstance(row.get("intake"), dict) else {}
            agent = row.get("agent") if isinstance(row.get("agent"), dict) else {}
            calls = tool_calls(row)

            status = "FLAGGED" if findings else "OK"
            route_label = route.get("action") or "legacy"
            route_reason = route.get("reason") or "-"
            intent = intake.get("intent") or "None"
            should_search = intake.get("should_search")

            lines.extend(
                [
                    f"#### Turn {turn_index}: `{status}` / route `{route_label}` / reason `{route_reason}`",
                    "",
                    f"- Message ID: `{row.get('message_id')}`",
                    f"- Intent: `{intent}`",
                    f"- Should search: `{should_search}`",
                    f"- Tool calls: `{len(calls)}`",
                ]
            )
            if findings:
                lines.append("- Findings: " + ", ".join(f"`{finding.severity}:{finding.code}`" for finding in findings))
            lines.extend(["", "**Cliente:**", "", blockquote(row.get("user_message"), answer_limit), ""])

            expected = row.get("expected_assistant")
            if expected:
                lines.extend(["**Agente viejo:**", "", blockquote(expected, answer_limit), ""])

            answer = agent.get("answer")
            if answer:
                lines.extend(["**Agente nuevo:**", "", blockquote(answer, answer_limit), ""])
            elif row.get("error"):
                lines.extend(["**Error:**", "", blockquote(row.get("error"), answer_limit), ""])
            else:
                lines.extend(["**Agente nuevo:**", "", "> Sin respuesta registrada.", ""])

            if calls:
                lines.extend(["**Búsquedas/tool calls:**", "", f"```json\n{json.dumps(calls, ensure_ascii=False, indent=2)}\n```", ""])

            state_after = row.get("state_after")
            route_dump = row.get("route")
            compact = {
                "route": route_dump,
                "state_after": {
                    "intent": state_after.get("intent") if isinstance(state_after, dict) else None,
                    "known": state_after.get("known") if isinstance(state_after, dict) else None,
                    "missing": state_after.get("missing") if isinstance(state_after, dict) else None,
                    "should_search": state_after.get("should_search") if isinstance(state_after, dict) else None,
                },
            }
            lines.extend(["**Estado resumido:**", "", f"```json\n{json.dumps(compact, ensure_ascii=False, indent=2)}\n```", ""])

        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def analyze_row(row: dict[str, Any]) -> list[Finding]:
    findings: list[Finding] = []
    user_message = text(row.get("user_message"))
    answer = text((row.get("agent") or {}).get("answer"))
    state_before = row.get("state_before") if isinstance(row.get("state_before"), dict) else {}
    state_after = row.get("state_after") if isinstance(row.get("state_after"), dict) else {}
    intake = row.get("intake") if isinstance(row.get("intake"), dict) else {}
    calls = tool_calls(row)

    if row.get("error"):
        findings.append(Finding("runtime_error", "high", str(row.get("error"))))

    if isinstance(row.get("agent"), dict) and not answer and not row.get("error"):
        findings.append(Finding("missing_answer", "high", "No agent answer in shadow row."))

    if calls and is_operational_or_closing(user_message):
        findings.append(Finding("tool_on_operational_message", "high", "Operational/closing message triggered product search."))

    if calls and is_short_or_low_context(user_message) and not likely_product_short_reply(user_message, state_before):
        findings.append(Finding("tool_on_short_followup", "medium", "Very short follow-up triggered product search."))

    if state_after.get("should_search") is True and not calls and answer and not is_derivation_answer(answer):
        findings.append(Finding("search_ready_without_tool", "high", "Intake says search is ready but no tool call was made."))

    if has_product_links(answer) and not calls:
        findings.append(Finding("product_links_without_tool", "high", "Answer contains product links without a tool call."))

    if is_generic_greeting(answer) and has_meaningful_context(row):
        findings.append(Finding("generic_greeting_with_context", "medium", "Agent greeted/menued despite conversation context."))

    repeated_slots = repeated_slot_questions(answer, user_message, state_before, state_after)
    for slot in repeated_slots:
        findings.append(Finding(f"repeated_slot_{slot}", "medium", f"Asked for {slot} although it seems already known."))

    if len(answer) > 1800:
        findings.append(Finding("very_long_answer", "low", "Answer may be too long for WhatsApp."))

    if old_odranid_domain(answer):
        findings.append(Finding("old_odranid_domain", "medium", "Answer uses odranid.com/producto instead of current catalog domain."))

    if "rollos" in norm(answer) and "metro lineal" in norm(answer):
        findings.append(Finding("mixed_rollo_and_meter_lineal", "medium", "Answer mixes rollos and metro lineal; review coverage wording."))

    if answer and intake.get("intent") == "pisos" and state_after.get("should_search") is False and no_actionable_question(answer):
        findings.append(Finding("floor_blocked_without_clear_question", "medium", "Floor intake is blocked but answer lacks a clear question."))

    return findings


def tool_calls(row: dict[str, Any]) -> list[dict[str, Any]]:
    calls = (row.get("agent") or {}).get("tool_calls")
    return calls if isinstance(calls, list) else []


def text(value: Any) -> str:
    return value if isinstance(value, str) else ""


def norm(value: str) -> str:
    value = value.lower()
    value = value.replace("á", "a").replace("é", "e").replace("í", "i").replace("ó", "o").replace("ú", "u")
    value = value.replace("ñ", "n")
    return value


def is_operational_or_closing(message: str) -> bool:
    value = norm(message)
    product_terms = [
        "piso",
        "manguera",
        "juguete",
        "perro",
        "gato",
        "tejo",
        "regaton",
        "pata",
        "tope",
        "goma",
        "vinilico",
        "simil madera",
    ]
    stock_terms = ["stock", "disponible", "disponibilidad", "tenes", "tienen"]
    if any(term in value for term in stock_terms) and any(term in value for term in product_terms):
        return False

    terms = [
        "gracias",
        "muchas gracias",
        "como compro",
        "como comprar",
        "pago",
        "efectivo",
        "transferencia",
        "tarjeta",
        "mercado libre",
        "mercadolibre",
        "ml",
        "retiro",
        "retirar",
        "envio",
        "envios",
        "asesor",
        "humano",
        "gerente",
        "respondido",
        "responden",
    ]
    return any(term in value for term in terms)


def is_short_or_low_context(message: str) -> bool:
    value = norm(message).strip()
    words = re.findall(r"\w+", value)
    return len(words) <= 3


def likely_product_short_reply(message: str, state_before: dict[str, Any]) -> bool:
    value = norm(message)
    clean = re.sub(r"[^\w\s]", " ", value)
    clean = re.sub(r"\s+", " ", clean).strip()
    known = state_before.get("known")
    if isinstance(known, dict) and known and clean in {"si", "si por favor", "dale", "dale por favor", "ok", "ok por favor"}:
        return True
    product_terms = [
        "piso",
        "manguera",
        "tejo",
        "tejos",
        "goma",
        "madera",
        "moneda",
        "semilla",
        "liso",
        "rayado",
    ]
    if any(term in value for term in product_terms):
        return True
    pending_slot = state_before.get("pending_slot")
    if pending_slot and re.search(r"\d", value):
        return True
    return bool(re.search(r"\b\d+(?:[.,]\d+)?\s*(?:mm|m|mts|metro|metros|m2)\b", value))


def has_product_links(answer: str) -> bool:
    value = norm(answer)
    return "odranid.com" in value and "/producto/" in value


def is_generic_greeting(answer: str) -> bool:
    value = norm(answer)
    return "soy el asistente virtual" in value or "decime que necesitas" in value or "pisos de goma, mangueras" in value


def is_derivation_answer(answer: str) -> bool:
    value = norm(answer)
    return "asesor especializado" in value or "wa.me/5491125539459" in value


def has_meaningful_context(row: dict[str, Any]) -> bool:
    history = row.get("history")
    state_before = row.get("state_before")
    route = row.get("route")
    if isinstance(route, dict) and route.get("clear_state") is True:
        return False
    if isinstance(state_before, dict) and state_before.get("known"):
        return True
    if isinstance(history, list):
        user_messages = [message for message in history if isinstance(message, dict) and message.get("role") == "user"]
        return len(user_messages) > 0
    return False


def repeated_slot_questions(
    answer: str,
    user_message: str,
    state_before: dict[str, Any],
    state_after: dict[str, Any],
) -> list[str]:
    answer_norm = norm(answer)
    user_norm = norm(user_message)
    known: dict[str, Any] = {}
    for state in [state_before, state_after]:
        state_known = state.get("known") if isinstance(state, dict) else None
        if isinstance(state_known, dict):
            known.update(state_known)

    repeated: list[str] = []
    slot_patterns = {
        "ancho": ["que ancho", "el ancho", "ancho buscas", "ancho preferis"],
        "espesor": ["que espesor", "el espesor", "espesor buscas", "espesor preferis"],
        "m2": ["cuantos m", "metros cuadrados", "necesitas cubrir"],
        "diseno": ["liso o con", "con diseno", "con diseño", "tipo de piso"],
    }
    slot_known = {
        "ancho": known.get("ancho_m") is not None or bool(re.search(r"\b\d+(?:[.,]\d+)?\s*(?:m|mts|metro|metros)\b", user_norm)),
        "espesor": known.get("espesor_mm") is not None or bool(re.search(r"\b\d+(?:[.,]\d+)?\s*mm\b", user_norm)),
        "m2": known.get("requested_m2") is not None or "m2" in user_norm or "metro cuadrado" in user_norm,
        "diseno": bool(known.get("floor_kind") or known.get("floor_design") or known.get("style_preference")),
    }
    for slot, patterns in slot_patterns.items():
        if slot_known[slot] and any(pattern in answer_norm for pattern in patterns):
            repeated.append(slot)
    return repeated


def old_odranid_domain(answer: str) -> bool:
    value = norm(answer)
    return "https://odranid.com/producto/" in value


def no_actionable_question(answer: str) -> bool:
    if "?" not in answer and "¿" not in answer:
        return True
    value = norm(answer)
    useful_terms = [
        "ancho",
        "espesor",
        "m2",
        "metros cuadrados",
        "liso",
        "diseno",
        "diseño",
        "uso",
        "usar",
        "usarlo",
        "para que lo vas",
    ]
    return not any(term in value for term in useful_terms)


def compact_state(state: Any) -> str:
    if not isinstance(state, dict):
        return "{}"
    compact = {
        "intent": state.get("intent"),
        "known": state.get("known"),
        "missing": state.get("missing"),
        "should_search": state.get("should_search"),
    }
    return one_line(json.dumps(compact, ensure_ascii=False), 500)


def compact_state_json(state: Any) -> str:
    if not isinstance(state, dict):
        return "{}"
    compact = {
        "intent": state.get("intent"),
        "known": state.get("known"),
        "missing": state.get("missing"),
        "should_search": state.get("should_search"),
    }
    return json.dumps(compact, ensure_ascii=False, indent=2)


def one_line(value: Any, limit: int) -> str:
    raw = text(value).replace("\n", " ").strip()
    raw = re.sub(r"\s+", " ", raw)
    if len(raw) <= limit:
        return raw
    return raw[: limit - 1].rstrip() + "…"


def blockquote(value: Any, limit: int) -> str:
    raw = text(value).strip()
    if len(raw) > limit:
        raw = raw[: limit - 1].rstrip() + "…"
    return "\n".join(f"> {line}" if line else ">" for line in raw.splitlines())


if __name__ == "__main__":
    main()
